//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Profile.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    
        public virtual User User { get; set; }
    }
}
