//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Profile.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public Respons()
        {
            this.UserResponses = new HashSet<UserRespons>();
        }
    
        public long ID { get; set; }
        public long AttributeID { get; set; }
        public string Responses { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual ICollection<UserRespons> UserResponses { get; set; }
    }
}
