//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Profile.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TICPuppyLoveProfileEntities : DbContext
    {
        public TICPuppyLoveProfileEntities()
            : base("name=TICPuppyLoveProfileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<ProfileChocy> ProfileChocies { get; set; }
        public virtual DbSet<Ref_ChoiceType> Ref_ChoiceType { get; set; }
        public virtual DbSet<Ref_QuestionType> Ref_QuestionType { get; set; }
        public virtual DbSet<Respons> Responses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRespons> UserResponses { get; set; }
    }
}
