//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Profile.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public long ID { get; set; }
        public long PhotoTypeID { get; set; }
        public long UserID { get; set; }
        public bool IsPrimary { get; set; }
        public string PhotoImage { get; set; }
    
        public virtual Ref_PhotoType Ref_PhotoType { get; set; }
        public virtual User User { get; set; }
    }
}
