//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Profile.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_ResponseType
    {
        public Ref_ResponseType()
        {
            this.Attributes = new HashSet<Attribute>();
            this.UserResponses = new HashSet<UserRespons>();
            this.Responses = new HashSet<Respons>();
        }
    
        public long ID { get; set; }
        public string ResponseType { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<UserRespons> UserResponses { get; set; }
        public virtual ICollection<Respons> Responses { get; set; }
    }
}
