//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Profile.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRespons
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long ResponseID { get; set; }
        public long QuestionTypeID { get; set; }
        public long ResponseTypeID { get; set; }
    
        public virtual Ref_QuestionType Ref_QuestionType { get; set; }
        public virtual User User { get; set; }
        public virtual Ref_ResponseType Ref_ResponseType { get; set; }
        public virtual Respons Respons { get; set; }
    }
}
