//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIC.PuppyLove.Services.Logic.Config.ConfigResource", typeof(ConfigResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Configurations Failed.
        /// </summary>
        internal static string AddUpdateConfigurationsFailed {
            get {
                return ResourceManager.GetString("AddUpdateConfigurationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Configuration Entries, Method Name: .
        /// </summary>
        internal static string AddUpdateConfigurationsOp {
            get {
                return ResourceManager.GetString("AddUpdateConfigurationsOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Configurations Successful.
        /// </summary>
        internal static string AddUpdateConfigurationsSuccess {
            get {
                return ResourceManager.GetString("AddUpdateConfigurationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must contain either a positive ID value or valid Name value.
        /// </summary>
        internal static string BadRequestMsg {
            get {
                return ResourceManager.GetString("BadRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ID and Name were supplied in request - Lookup will be performed by ID.
        /// </summary>
        internal static string BothIdAndNameReceived {
            get {
                return ResourceManager.GetString("BothIdAndNameReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Configurations Failed.
        /// </summary>
        internal static string DeleteConfigurationsFailed {
            get {
                return ResourceManager.GetString("DeleteConfigurationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Configuration Entries, Method Name: .
        /// </summary>
        internal static string DeleteConfigurationsOp {
            get {
                return ResourceManager.GetString("DeleteConfigurationsOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Configurations Successful.
        /// </summary>
        internal static string DeleteConfigurationsSuccess {
            get {
                return ResourceManager.GetString("DeleteConfigurationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Data Recieved - ID: {0}, Name: {1}, Value: {2}.
        /// </summary>
        internal static string EchoConfigEntry {
            get {
                return ResourceManager.GetString("EchoConfigEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Response Status is: {0} and the Response Message is: {1}.
        /// </summary>
        internal static string EchoResponseObj {
            get {
                return ResourceManager.GetString("EchoResponseObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Operation: .
        /// </summary>
        internal static string EndOfOperation {
            get {
                return ResourceManager.GetString("EndOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR encountered in operation {0}.
        /// </summary>
        internal static string ErrorInOperation {
            get {
                return ResourceManager.GetString("ErrorInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Configuration Entries, Method Name: .
        /// </summary>
        internal static string GetAllConfigEntriesOp {
            get {
                return ResourceManager.GetString("GetAllConfigEntriesOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Configurations Failed.
        /// </summary>
        internal static string GetAllConfigurationsFailed {
            get {
                return ResourceManager.GetString("GetAllConfigurationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Configurations Successful.
        /// </summary>
        internal static string GetAllConfigurationsSuccess {
            get {
                return ResourceManager.GetString("GetAllConfigurationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Specific Configuration Entries, Method Name: .
        /// </summary>
        internal static string GetSpecificConfigEntriesOp {
            get {
                return ResourceManager.GetString("GetSpecificConfigEntriesOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Specific Configurations Failed.
        /// </summary>
        internal static string GetSpecificConfigurationsFailed {
            get {
                return ResourceManager.GetString("GetSpecificConfigurationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Specific Configuration Successful.
        /// </summary>
        internal static string GetSpecificConfigurationsSuccess {
            get {
                return ResourceManager.GetString("GetSpecificConfigurationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception Received: .
        /// </summary>
        internal static string InnerExceptionReceived {
            get {
                return ResourceManager.GetString("InnerExceptionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Configuration Entries Match the Criteria Provided.
        /// </summary>
        internal static string NoConfigEntriesFound {
            get {
                return ResourceManager.GetString("NoConfigEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Configuration resulted in deletion of {0} rows.
        /// </summary>
        internal static string NumRowsDeleted {
            get {
                return ResourceManager.GetString("NumRowsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request object contained no valid entires - operation aborted.
        /// </summary>
        internal static string OperationAborted {
            get {
                return ResourceManager.GetString("OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string strNULL {
            get {
                return ResourceManager.GetString("strNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some input records were incomplete and discarded.
        /// </summary>
        internal static string WarnInputRecsDiscarded {
            get {
                return ResourceManager.GetString("WarnInputRecsDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Received request to delete {0} IDs but only {1} available in DB for deletion.
        /// </summary>
        internal static string WarnNotAllDeleted {
            get {
                return ResourceManager.GetString("WarnNotAllDeleted", resourceCulture);
            }
        }
    }
}
