//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIC.PuppyLove.Services.Logic.Profile.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Creation, Method Name:.
        /// </summary>
        internal static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for parameters - UserID: {0}.
        /// </summary>
        internal static string EchoPhotoSearchCriteria {
            get {
                return ResourceManager.GetString("EchoPhotoSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Operation: .
        /// </summary>
        internal static string EndOfOperation {
            get {
                return ResourceManager.GetString("EndOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR encountered in operation {0}.
        /// </summary>
        internal static string ErrorInOperation {
            get {
                return ResourceManager.GetString("ErrorInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile GetMatchProfileChoiceStatus Method Name.
        /// </summary>
        internal static string GetMatchProfileChoiceStatus {
            get {
                return ResourceManager.GetString("GetMatchProfileChoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Get Photos By User ID Method Name: .
        /// </summary>
        internal static string GetPhotosByUserID {
            get {
                return ResourceManager.GetString("GetPhotosByUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Get Photo Types Method Name: .
        /// </summary>
        internal static string GetPhotoTypes {
            get {
                return ResourceManager.GetString("GetPhotoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Get Primary Photo Method Name: .
        /// </summary>
        internal static string GetPrimaryPhoto {
            get {
                return ResourceManager.GetString("GetPrimaryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile GetProfileData Method Name.
        /// </summary>
        internal static string GetProfileData {
            get {
                return ResourceManager.GetString("GetProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile GetQuestions Method Name.
        /// </summary>
        internal static string GetQuestions {
            get {
                return ResourceManager.GetString("GetQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception Received: .
        /// </summary>
        internal static string InnerExceptionReceived {
            get {
                return ResourceManager.GetString("InnerExceptionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Login, Method Name:.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rows Returned From Profile Photo Search: {0}.
        /// </summary>
        internal static string RowsReturnedFromPhotoSearch {
            get {
                return ResourceManager.GetString("RowsReturnedFromPhotoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile UpdateProfile Method Name.
        /// </summary>
        internal static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile ValidateLoginUserName Method Name.
        /// </summary>
        internal static string ValidateLoginUserName {
            get {
                return ResourceManager.GetString("ValidateLoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID Must Be Greater Than Zero.  Operation Aborted..
        /// </summary>
        internal static string ValidateUserIDMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ValidateUserIDMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
