//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIC.PuppyLove.Services.Logic.Location {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIC.PuppyLove.Services.Logic.Location.LocationResource", typeof(LocationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Request Object is NULL or missing data - Operation Terminated.
        /// </summary>
        internal static string BadRequestObject {
            get {
                return ResourceManager.GetString("BadRequestObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Input Data Received is: Lat: {0}, Long: {1}, UserID: {2}, Accuracy: {3}, Timestamp: {4}.
        /// </summary>
        internal static string EchoLocationData {
            get {
                return ResourceManager.GetString("EchoLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Input Data Received is: Lat: {0}, Long: {1}, RadiusMiles: {2}, UserID: {3}.
        /// </summary>
        internal static string EchoNearestNeighborRequest {
            get {
                return ResourceManager.GetString("EchoNearestNeighborRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Response Status is: {0} and the Response Message is: {1}.
        /// </summary>
        internal static string EchoResponseObj {
            get {
                return ResourceManager.GetString("EchoResponseObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR WAS ENCOUNTERED BY ENTITY FRAMEWORK IN OPERATION {0}: {1}.
        /// </summary>
        internal static string EF_ErrorInOperation {
            get {
                return ResourceManager.GetString("EF_ErrorInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Operation: .
        /// </summary>
        internal static string EndOfOperation {
            get {
                return ResourceManager.GetString("EndOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR encountered in operation {0}.
        /// </summary>
        internal static string ErrorInOperation {
            get {
                return ResourceManager.GetString("ErrorInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current Locations Failed.
        /// </summary>
        internal static string GetCurrentLocationsFailed {
            get {
                return ResourceManager.GetString("GetCurrentLocationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Locations, Method Name: .
        /// </summary>
        internal static string GetCurrentLocationsOp {
            get {
                return ResourceManager.GetString("GetCurrentLocationsOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current Locations Successful.
        /// </summary>
        internal static string GetCurrentLocationsSuccess {
            get {
                return ResourceManager.GetString("GetCurrentLocationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nearest Neighbors Failed.
        /// </summary>
        internal static string GetNearestNeighborsFailed {
            get {
                return ResourceManager.GetString("GetNearestNeighborsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nearest Neighbors, Method Name: .
        /// </summary>
        internal static string GetNearestNeighborsOp {
            get {
                return ResourceManager.GetString("GetNearestNeighborsOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nearest Neighbors Successful.
        /// </summary>
        internal static string GetNearestNeighborsSuccess {
            get {
                return ResourceManager.GetString("GetNearestNeighborsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProfileDataOp.
        /// </summary>
        internal static string GetProfileDataOp {
            get {
                return ResourceManager.GetString("GetProfileDataOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Get, Method Name: .
        /// </summary>
        internal static string GetUserDataOp {
            get {
                return ResourceManager.GetString("GetUserDataOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exception Message Found.
        /// </summary>
        internal static string InnerMessageNotFound {
            get {
                return ResourceManager.GetString("InnerMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Lookup by UserID was NOT Found in the Location Table..
        /// </summary>
        internal static string LocationLookupNotFound {
            get {
                return ResourceManager.GetString("LocationLookupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Location Record Was Not Deleted.
        /// </summary>
        internal static string NoRecordsDeleted {
            get {
                return ResourceManager.GetString("NoRecordsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Location Record Was Not Inserted or Updated.
        /// </summary>
        internal static string NoRecordsInsertedOrUpdated {
            get {
                return ResourceManager.GetString("NoRecordsInsertedOrUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No User ID supplied - All Locations Returned With No Distance Calculation.
        /// </summary>
        internal static string NoUserIdSupplied {
            get {
                return ResourceManager.GetString("NoUserIdSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileServiceUrl.
        /// </summary>
        internal static string ProfileServiceUrl {
            get {
                return ResourceManager.GetString("ProfileServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Location Failed.
        /// </summary>
        internal static string RemoveFailed {
            get {
                return ResourceManager.GetString("RemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Remove, Method Name: .
        /// </summary>
        internal static string RemoveOp {
            get {
                return ResourceManager.GetString("RemoveOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Remove Wrapper for NewtonSoft, Method Name: .
        /// </summary>
        internal static string RemoveOpNewt {
            get {
                return ResourceManager.GetString("RemoveOpNewt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Location Successful.
        /// </summary>
        internal static string RemoveSuccessful {
            get {
                return ResourceManager.GetString("RemoveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Location Failed.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Add/Update, Method Name: .
        /// </summary>
        internal static string UpdateOp {
            get {
                return ResourceManager.GetString("UpdateOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Add/Update Wrapper for NewtonSoft, Method Name: .
        /// </summary>
        internal static string UpdateOpNewt {
            get {
                return ResourceManager.GetString("UpdateOpNewt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Location Successful.
        /// </summary>
        internal static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful now retrieve location row from db for UI.
        /// </summary>
        internal static string UpdateWorkedGetLocRecord {
            get {
                return ResourceManager.GetString("UpdateWorkedGetLocRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request contains UserID.  Operation will lookup Lat/Long from database and ignore Lat/Long passed in the request..
        /// </summary>
        internal static string UserIdFound {
            get {
                return ResourceManager.GetString("UserIdFound", resourceCulture);
            }
        }
    }
}
